title: Faisal Khan's Professional Portfolio
author: Faisal Khan
description: "Contact me at |Email:faisal.khan@uconn.edu|Phone:860-123-4567|Location:South Windsor, CT"
theme: minima

header_pages:
 - blog.md
 - projects.md
 - index.md





