title: Faisal Khan's Professional Portfolio
author: Faisal Khan
description: "As part of my undergraduate journey, I have had the opportunity to work on several impactful projects. Below are some highlgihts:"
theme: minima

header_pages:
 - blog.md
 - projects.md
 - index.md



